version: '3'
services:
  mock-mosaic-maker:
    image: ryanjvanvoorhis/mock-mosaic-maker
    environment:
      - MOSAIC_API_URL=${MOSAIC_API_URL}
    ports:
      - ${MOCK_MOSAIC_EXTERNAL_PORT}:5080

  mosaic-api:
    build: .
    image: ryanjvanvoorhis/mosaic-api
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - SECRET_KEY=${SECRET_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_EXTERNAL_URL=${S3_EXTERNAL_URL}
      - MOSAIC_API_URL_INTERNAL=${MOSAIC_API_URL_INTERNAL}
      - MOSAIC_API_URL_EXTERNAL=http://${BROADCAST_IP}:${MOSAIC_API_PORT}/api/v1/photomosaic
      - FRONT_END_URL=http://{$BROADCAST_IP}:${FE_PORT}
      - FAAS_URL=http://${PHOTOMOSAIC_DOMAIN}:${PHOTOMOSAIC_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - ${MOSAIC_API_PORT}:5000

  local-s3:
    user: root
    image: andrewgaul/s3proxy
    ports:
      - ${S3_PORT}:80
    environment:
      - S3PROXY_AUTHORIZATION=none
    volumes:
      - ${S3_DATA_DIRECTORY}:/data

  mongodb:
    user: root
    image: bitnami/mongodb:latest
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - ${MONGODB_DATA_DIRECTORY}:/bitnami
