provider:
  name: faas
  gateway: http://___BROADCAST_IP___:8080

functions:
  mosaic-healthcheck:
    skip_build: true
    image: ryanjvanvoorhis/mosaic-healthcheck:latest
    environment:
     MOSAIC_API_URL: http://mosaic-api:5000/api/v1/photomosaic

  mosaic-maker:
    image: ryanjvanvoorhis/mosaic-maker:latest
    skip_build: true
    environment:
      MOSAIC_API_URL: http://mosaic-api:5000/api/v1/photomosaic